FROM nginx:1.23.2
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./oberacker_me.ca-bundle.pem /etc/nginx/certs/oberacker_me.ca-bundle.pem
COPY ./oberacker_me.key.pem /etc/nginx/certs/oberacker_me.key.pem